[tool.poetry]
name = "invalid"
description = "Invalid Extension"
version="0.1.0"
authors=["author"]
packages = [
    {include = "../"}
]

[tool.poetry.dependencies]
# Clashing dependency
python = "3.5"